language: node_js
node_js:
  - 10
install:
  - npm install -g codecov
script:
  - npm run test
  - nyc report --reporter=text-lcov --require @babel/register > coverage.lcov && yarn codecov
  - codecov
